### ISSUE TITLE
no certificate on /etc/puppetlabs/puppet/ssl/certs/

### ISSUE THREAD

**Issue by empereira** [slimjim2234/docker-foreman#1]
Hello,

The error below occurs:

> SSLCertificateFile: file '/etc/puppetlabs/puppet/ssl/certs/foreman.lab.pem' does not exist or is empty

**Comment by slimjim2234** [comment]
thanks for submitting the issue.  This repo is now defunct since the foreman project has implemented an official docker compose file for the project.
https://github.com/theforeman/foreman/blob/develop/docker-compose.yml
